# Generated by Django 5.1.6 on 2025-03-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
